import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import LandingImg from '../components/LandingImg'
import PlanCarousel from '../components/PlanCarousel'
import PlanSteps from '../components/PlanSteps'
import FamilyPlan from '../components/FamilyPlan'
import PhoneCarousel from '../components/PhonesCarousel'
import SavingsCalculator from '../components/SavingsCalculator'
import Footer from '../components/Footer'

export default function Home() {

  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.background} id="background">
          <LandingImg />
          <FamilyPlan />
          <PlanCarousel />
          <PlanSteps />
          <PhoneCarousel />
          <SavingsCalculator />
          <Footer />
        </div>
      </div>
    </>
  )
}
